databases:
  - name: superplane-db
    plan: free
    databaseName: superplane
    user: superplane

services:
  - type: web
    name: superplane
    runtime: docker
    repo: https://github.com/JzJoker/superplane
    branch: main
    previews:
      generation: automatic
    envVars:
      - key: APPLICATION_NAME
        value: superplane
      - key: DB_HOST
        fromDatabase:
          name: superplane-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: superplane-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: superplane-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: superplane-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: superplane-db
          property: database
      - key: POSTGRES_DB_SSL
        value: "false"
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        value: "https://superplane.onrender.com"
      - key: WEBHOOKS_BASE_URL
        value: "https://superplane.onrender.com"
      - key: PUBLIC_API_BASE_PATH
        value: "/api/v1"
      - key: START_PUBLIC_API
        value: "yes"
      - key: OIDC_KEYS_PATH
        value: "/app/test/fixtures/oidc-keys"
      - key: RBAC_MODEL_PATH
        value: "/app/rbac/rbac_model.conf"
      - key: RBAC_ORG_POLICY_PATH
        value: "/app/rbac/rbac_org_policy.csv"
